DROP DATABASE test;
CREATE DATABASE test;
USE test;
CREATE TABLE dummy
(
	ID int NOT NULL,
	NAME  varchar(50) NOT NULL,	
	PRIMARY KEY(ID)
);


CREATE TABLE ACTIVITY
(
	ID int NOT NULL,
	USER_ID int NOT NULL,
	EQUIPMENT_ID int NOT NULL,
	AC_DATE DATETIME NOT NULL,
	ENTERING boolean NOT NULL,
	PRIMARY KEY(ID)
);


INSERT INTO dummy VALUES (0,"dummy1");
INSERT INTO dummy VALUES (1,"dummy2");